repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    -   id: flake8
-   repo: local
    hooks:
    -   id: black
        # Using local black because it won't work for me from remote repo -EJ
        name: black
        entry: black
        language: system
        types: [python]
        stages: [commit]
