name: Run Tests
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: FedericoCarboni/setup-ffmpeg@v1
        id: setup-ffmpeg

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.7"
          cache: "pip"

      - name: Install Python dependencies
        run: |
          # Install all Python dependencies in just one pip call, including Studio itself
          pip install -r requirements.txt \
                      -r requirements.dev.txt \
                      -r requirements.ci.txt \
                      -e .
          # Legal check: make sure we don't have or introduce GPL dependencies
          if pip-licenses | grep -v 'Artistic License' | grep -v LGPL | grep GNU; then echo 'Please avoid introducing *GPL dependencies'; false; fi

      - name: Run tests
        run: |
          gunicorn readalongs.app:app --bind 0.0.0.0:5000 --daemon
          cd test && coverage run run.py prod && coverage xml

      - name: coding style nit-picking, we want black compliance
        run: find . -name \*.py | xargs black --check

      - uses: codecov/codecov-action@v2
        with:
          directory: ./test
          fail_ci_if_error: true # optional (default = false)
