name: Run Tests
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    # #no-ci in the commit log flags commit we don't want CI-validated
    if: ${{ !contains(github.event.head_commit.message, '#no-ci') }}
    steps:
      - uses: actions/checkout@v3

      - uses: FedericoCarboni/setup-ffmpeg@v2
        id: setup-ffmpeg

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"
          cache: "pip"

      - name: Install Python dependencies
        run: |
          # Some dependencies are built using wheel
          pip install wheel
          # Install all Python dependencies in just one pip call, including Studio itself
          pip install -r requirements.txt \
                      -r requirements.dev.txt \
                      -r requirements.ci.txt \
                      -e .

      - name: Run tests
        run: |
          gunicorn readalongs.app:app --bind 0.0.0.0:5000 --daemon
          cd test && coverage run run.py prod && coverage xml

      - name: Nitpicking
        run: |
          # coding style: we want black compliance
          find . -name \*.py | xargs black --check
          # Legal check: make sure we don't have or introduce GPL dependencies
          if pip-licenses | grep -v 'Artistic License' | grep -v LGPL | grep GNU; then echo 'Please avoid introducing *GPL dependencies'; false; fi

      - uses: codecov/codecov-action@v3
        with:
          directory: ./test
          fail_ci_if_error: true # optional (default = false)

  test-on-windows:
    runs-on: windows-latest
    if: ${{ !contains(github.event.head_commit.message, '#no-ci') }}
    steps:
      - uses: actions/checkout@v3

      - uses: FedericoCarboni/setup-ffmpeg@v2
        id: setup-ffmpeg

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"
          cache: "pip"

      - name: Install Python dependencies
        run: |
          pip install wheel
          pip install -r requirements.txt `
                      -r requirements.dev.txt `
                      -r requirements.ci.txt `
                      -e .

      - name: Run tests on Windows
        run: cd test && python run.py prod
